// <auto-generated />
using System;
using BulsLogAgendamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulsLogAgendamento.Migrations
{
    [DbContext(typeof(BulsLogAgendamentoContext))]
    [Migration("20230108164711_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BulsLogAgendamento.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Container");

                    b.Property<DateTime>("Data_Escolhida");

                    b.Property<DateTime>("Data_Limite");

                    b.Property<string>("NF");

                    b.Property<string>("Numero_Book");

                    b.HasKey("Id");

                    b.ToTable("Agendamento");
                });
#pragma warning restore 612, 618
        }
    }
}
